apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: addons-sealed-secrets
spec:
  goTemplate: true
  goTemplateOptions: [ "missingkey=error" ]
  applyNestedSelectors: true
  syncPolicy:
    preserveResourcesOnDeletion: false
  generators:
    - merge:
        mergeKeys: [server]
        generators:
          - clusters:
              values:
                addonChart: sealed-secrets
                addonChartNamespace: kube-system
                addonChartVersion: 2.17.1
                addonChartRepository: https://bitnami-labs.github.io/sealed-secrets/
              selector:
                matchExpressions:
                  - key: argocd.argoproj.io/secret-type
                    operator: In
                    values: [cluster]
                  - key: enable_sealed_secrets
                    operator: In
                    values: ['true']
          - clusters:
              selector:
                matchLabels:
                  environment: staging
              values:
                addonChartVersion: 2.17.1
  template:
    metadata:
      name: addon-{{.values.addonChart}}
    spec:
      project: default
      sources:
        - chart: '{{.values.addonChart}}'
          repoURL: '{{.values.addonChartRepository}}'
          targetRevision: '{{.values.addonChartVersion}}'
          helm:
            releaseName: '{{.values.addonChart}}-controller'
            valuesObject:
              fullnameOverride: sealed-secrets
              # disable key rotation
              keyrenewperiod: "0"
              # update unsealing status, required for ArgoCD
              # to detect that SealedSecret was synced and unsealed successfully
              updateStatus: true
      destination:
        namespace: '{{.values.addonChartNamespace}}'
        name: '{{.name}}'
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
