apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: addons-sealed-secrets
spec:
  goTemplate: true
  goTemplateOptions: [ "missingkey=error" ]
  applyNestedSelectors: true
  syncPolicy:
    preserveResourcesOnDeletion: false
  generators:
    - merge:
        - clusters:
            values:
              addonChart: sealed-secrets
              addonChartNamespace: kube-system
              addonChartVersion: 2.17.1
              addonChartRepository: https://bitnami-labs.github.io/sealed-secrets/
            selector:
              matchExpressions:
                - key: argocd.argoproj.io/secret-type
                  operator: In
                  values: [cluster]
                - key: enable_sealed_secrets
                  operator: In
                  values: ['true']
        - clusters:
            selector:
              matchLabels:
                environment: different-cluster
            values:
              addonChartVersion: 2.16.2
  template:
    metadata:
      name: addon-{{.values.addonChart}}
      labels:
        managed-by: ApplicationSet
    spec:
      project: default
      sources:
        - chart: '{{.values.addonChart}}'
          repoURL: '{{.values.addonChartRepository}}'
          targetRevision: '{{.values.addonChartVersion}}'
          helm:
            releaseName: '{{.values.addonChart}}-controller'
            valuesObject:
              fullnameOverride: sealed-secrets
              keyrenewperiod: "0"
              updateStatus: true
              resources:
                requests:
                  cpu: 5m
                  memory: 20Mi
                limits:
                  cpu: 100m
                  memory: 150Mi
      destination:
        namespace: '{{.values.addonChartNamespace}}'
        name: '{{.name}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
